const footerData = {
    shopAndLearn: [
      'Mac',
      'iPad',
      'iPhone',
      'Watch',
      'TV',
      'Music',
      'AirPods',
      'HomePod',
      'iPod touch',
      'Accessories',
      'Gift Cards',
    ],
    services: [
      'Apple Music',
      'Apple News+',
      'Apple TV+',
      'Apple Arcade',
      'Apple Card',
      'iCloud',
    ],
    account: [
      'Manage Your Apple ID',
      'Apple Store Account',
      'iCloud.com',
    ],
    appleStore: [
      'Find a Store',
      'Genius Bar',
      'Today at Apple',
      'Apple Camp',
      'Field Trip',
      'Apple Store App',
      'Refurbished and Clearance',
      'Financing',
      'Apple Trade In',
      'Order Status',
      'Shopping Help',
    ],
    business: ['Apple and Business', 'Shop for Business'],
    education: ['Apple and Education', 'Shop for College'],
    healthcare: ['Manage Your Apple ID', 'Apple Store Account', 'iCloud.com'],
    government: ['Apple and Education', 'Shop for College'],
    appleValues: [
      'Find a Store',
      'Genius Bar',
      'Today at Apple',
      'Apple Camp',
      'Field Trip',
      'Apple Store App',
    ],
    aboutApple: [
      'Find a Store',
      'Genius Bar',
      'Today at Apple',
      'Apple Camp',
      'Field Trip',
      'Apple Store App',
    ],
  }


export default footerData;
